### ISSUE TITLE
Publish docker image to dockerhub.

### ISSUE THREAD

**Issue by debendraoli** [jitsi/excalidraw-backend#5]
This would greatly facilitate users to use pre-built image.

I guess we need to package for debain first so that we can configure through `docker-jitsi-meet`.

**Comment by saghul** [comment]
We are still beta testing this.

**Comment by aslam-t** [comment]
Hey @saghul, is there update on this?

**Comment by saghul** [comment]
Not yet, sorry.

**Comment by saghul** [comment]
https://hub.docker.com/r/jitsi/excalidraw-backend
