### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by jindovu** [jitsi/excalidraw-backend#8]
When I install package and run project it's error, I'm trying to upgrade all package but it's still got issue, please help me to check that 

![image](https://user-images.githubusercontent.com/19401173/215258411-21867c95-f4d1-44dc-91ee-a8a880f829cf.png)

Thank you

**Comment by saghul** [comment]
You can't just update all packages. Dependencies are pinned for a reason.

**Comment by jindovu** [comment]
when I try to install package not upgrade yet it still have error, please have a look, I don't know what I'm missing from that 
![image](https://user-images.githubusercontent.com/19401173/215277244-54719565-cb82-4f55-a159-866b8ad7c951.png)

**Comment by saghul** [comment]
Did you just run npm install, without any changes?

**Comment by jindovu** [comment]
yes, I run npm install without any changes

**Comment by saghul** [comment]
What node and npm versions are you using?

**Comment by jindovu** [comment]
Please have a look on this
![image](https://user-images.githubusercontent.com/19401173/215335316-1b75ef07-27e4-46f5-9e86-95f69ce0fbda.png)

**Comment by saghul** [comment]
Please use Node 16 and npm 8.

**Comment by jindovu** [comment]
I already install Node 16 and npm 8 but it's still got same error, please check this 
![image](https://user-images.githubusercontent.com/19401173/215831936-3f710875-2a47-4146-a917-1d97f583ea77.png)

**Comment by saghul** [comment]
Are you sure you reverted to the socketio versions specified in the package? I have o la seen that error when numbing the socketio dependency to the latest version.

**Comment by jindovu** [comment]
ah yes, I already reverted & change to Node 16 and npm 8 it's worked, thank you for your help
